- name: Reboot Server
  hosts: all
  gather_facts: no
  tasks:
    - name: reboot the server
      become: yes
      command: sudo reboot
      async: 1
      poll: 0
      ignore_errors: true
    - name: Wait for the server to come back online
      local_action: wait_for host={{ inventory_hostname }} port=22 timeout=300 state=started

