---
- name: Check uptime on all servers
  hosts: all
  gather_facts: yes

  tasks:
    - name: Get uptime
      command: "uptime"
      register: result

    - name: Display uptime
      debug:
        var: result.stdout_lines
